### ISSUE TITLE
Soft-Launch Checklist

### ISSUE THREAD

**Issue by efstajas** [radicle-dev/drips-app-v2#324]
- [x] Update SDK once it adds support for mainnet contracts
- [x] Add legal copy somewhere (footer & account menu?)
- [x] Update beta notice copy to direct people to v1 app, given that the v2 app is still "in beta"
- [x] Add some kind of permanent "Drips v1" link somewhere for people that have previously used v1 (header? footer?)
- [x] Move v1 app to v1.drips.network
- [x] Move v2 app to drips.network

**Comment by efstajas** [comment]
@evvvritt fyi
